### ISSUE TITLE
Why it stops polling after payout request?

### ISSUE THREAD

**Issue by kolucciy** [kybarg/ssp#2]
![image](https://github.com/kybarg/ssp/assets/864854/4c174237-259d-4d56-9ed8-54b99ad89454)
Any idea?

**Comment by kybarg** [comment]
@kolucciy only `ENABLE` command is implemented as a method currently, for the rest needs to start polling device manually

Can implement something like this
```javascript
async function  payout(amount) {
    const result = await ssp.command('PAYOUT_BY_DENOMINATION', { amount })

    if (result.status === 'OK') {
      ssp.state.enabled = true
      if (!ssp.state.polling) await ssp.poll(true)
    }

    return result
  }
```

And to stop poplling
```javascript
ssp.poll(false)
```
